### ISSUE TITLE
Basic sample code

### ISSUE THREAD

**Issue by tariqshihadah** [tariqshihadah/cpm#1]
_**Welcome to the party!**_

We need to develop a simple, self-contained example of how to:

1. Import the package
2. Load a particular model
3. Create a data template
4. Populate the data template using an external editor
5. Analyze the templated data
6. Export the analysis results

Are there any additional steps that should be included in the initial example? Any changes/fixes that need to be completed before this is done?

**Comment by mahdirajabi96** [comment]
I added a sample dataset and sample calculations
